class TextHelper {
  static const String privacyPolicyText = '''Last updated: December 22, 2023

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.

Interpretation and Definitions

Interpretation

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions

For the purposes of this Privacy Policy:

Account means a unique account created for You to access our Service or parts of our Service.

Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.

Application refers to InvestIQator, the software program provided by the Company.

Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to InvestIQator.

Country refers to: California, United States

Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

Personal Data is any information that relates to an identified or identifiable individual.

Service refers to the Application.

Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

Collecting and Using Your Personal Data

Types of Data Collected

Personal Data

While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

Usage Data
Usage Data

Usage Data is collected automatically when using the Service.

Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.

We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.

Information Collected while Using the Application

While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:

Information regarding your location
We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.

You can enable or disable access to this information at any time, through Your Device settings.

Use of Your Personal Data

The Company may use Personal Data for the following purposes:

To provide and maintain our Service, including to monitor the usage of our Service.

To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.

For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.

To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.

To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.

To manage Your requests: To attend and manage Your requests to Us.

For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.

For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.

We may share Your personal information in the following situations:

With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
With Your consent: We may disclose Your personal information for any other purpose with Your consent.
Retention of Your Personal Data

The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.

Transfer of Your Personal Data

Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.

Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.

The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.

Delete Your Personal Data

You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.

Our Service may give You the ability to delete certain information about You from within the Service.

You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.

Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.

Disclosure of Your Personal Data

Business Transactions

If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.

Law enforcement

Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

Other legal requirements

The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:

Comply with a legal obligation
Protect and defend the rights or property of the Company
Prevent or investigate possible wrongdoing in connection with the Service
Protect the personal safety of Users of the Service or the public
Protect against legal liability
Security of Your Personal Data

The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

Children's Privacy

Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.

Links to Other Websites

Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

Changes to this Privacy Policy

We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

Contact Us

If you have any questions about this Privacy Policy, You can contact us:

By email: leducnguyen870@gmail.com''';
  static const String terms = '''Last updated: December 22, 2023

Please read these terms and conditions carefully before using Our Service.

Interpretation and Definitions

Interpretation

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions

For the purposes of these Terms and Conditions:

Application means the software program provided by the Company downloaded by You on any electronic device, named InvestIQator

Application Store means the digital distribution service operated and developed by Apple Inc. (Apple App Store) or Google Inc. (Google Play Store) in which the Application has been downloaded.

Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.

Country refers to: California, United States

Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to InvestIQator.

Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

Service refers to the Application.

Terms and Conditions (also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions agreement has been created with the help of the Free Terms and Conditions Generator.

Third-party Social Media Service means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.

You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

Acknowledgment

These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.

Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.

By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.

You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.

Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.

Links to Other Websites

Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company.

The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.

We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.

Termination

We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.

Upon termination, Your right to use the Service will cease immediately.

Limitation of Liability

Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You through the Service or 100 USD if You haven't purchased anything through the Service.

To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.

Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party's liability will be limited to the greatest extent permitted by law.

"AS IS" and "AS AVAILABLE" Disclaimer

The Service is provided to You "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.

Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.

Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.

Governing Law

The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.

Disputes Resolution

If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.

For European Union (EU) Users

If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which You are resident.

United States Legal Compliance

You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a "terrorist supporting" country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.

Severability and Waiver

Severability

If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.

Waiver

Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not affect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute a waiver of any subsequent breach.

Translation Interpretation

These Terms and Conditions may have been translated if We have made them available to You on our Service. You agree that the original English text shall prevail in the case of a dispute.

Changes to These Terms and Conditions

We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.

By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.

Contact Us

If you have any questions about these Terms and Conditions, You can contact us:

By email: leducnguyen870@gmail.com''';
  static const String rateUsText =
      '''We're constantly working to enhance your experience with our app! Your feedback matters a lot to us. Please, give 5 stars to our app in the AppStore page!''';
  static const String theoryText_1_1 =
      '''Investments are one of the essential tools for financial planning and achieving financial goals. Investments refer to long-term capital investments with the aim of generating profit or capital growth.\n
One of the key concepts in investments is risk. Risk is the possibility of losing part or all of the investment. Generally, the higher the investment's return, the higher the associated risk. Therefore, it is crucial to assess risk correctly and make decisions based on financial capabilities and goals.''';
  static const String theoryText_1_2 =
      '''Another important concept is return. Return is the profit gained from the investment expressed in percentage terms. It can be fixed (e.g., bond income) or variable (e.g., stock income). Considering both potential return and possible risks is essential when selecting investments.\n
Investment principles include diversification, technical and fundamental analysis, investment psychology, and long-term strategies.''';
  static const String theoryText_1_3 =
      '''Diversification involves distributing investments among different assets or instruments to reduce risk. Diversifying investments helps mitigate losses in case one asset performs poorly.\n
Technical analysis relies on price chart analysis and other data to forecast future price movements. It assumes that historical data can help predict future trends and market behavior.''';
  static const String theoryText_1_4 =
      '''Fundamental analysis is the evaluation of asset and company value based on financial indicators such as profit, current assets, debts, and others. Fundamental analysis aids in determining the asset's value and deciding whether to buy or sell.\n
Investment psychology plays a significant role in decision-making. Emotions like fear and greed can lead to irrational actions and financial losses. Therefore, maintaining composure and making decisions based on analysis and financial goals are crucial.''';
  static const String theoryText_1_5 =
      '''Long-term investment strategies aim at achieving financial goals in the long run. They include regular investments, portfolio rebalancing, and long-term planning.\n
In conclusion, understanding investment basics such as risk, return, diversification, analysis, and strategies is vital for successful investing. It enables making informed decisions and reaching financial goals.''';
  static const String theoryText_2_1 =
      '''Various types of investments provide investors with the opportunity to diversify their portfolios and achieve different financial goals. Some of the most common types of investments include stocks, bonds, real estate, and other assets.\n
      Stocks represent ownership shares in a company and are one of the most popular types of investments. Investors can purchase shares of public companies on the stock exchange and earn income in the form of dividends and capital appreciation. However, stocks are also associated with a high level of risk as their prices can fluctuate based on the financial health of the company and overall market conditions.''';
  static const String theoryText_2_2 =
      '''Bonds are debt instruments issued by governments or private companies to raise capital. Investors, by purchasing bonds, become creditors and receive interest payments over a specified period. Bonds are generally considered more stable and reliable investments compared to stocks, although their returns may be lower.\n
  Real estate is another popular investment vehicle. Investors can acquire properties such as apartments, houses, or commercial buildings with the aim of earning rental income or benefiting from the appreciation of property value. Real estate investments are often long-term and require careful market analysis and assessment of potential returns.''';
  static const String theoryText_2_3 =
      '''Additionally, there are various other types of investments, including commodities, currencies, funds, etc. These investments can provide investors with opportunities to protect their capital from inflation and generate income in volatile market conditions.\n
It's important to note that each type of investment has its own characteristics, risks, and potential returns. Therefore, thorough research of each investment type, evaluation of financial capabilities and goals, and consultation with a financial advisor or specialist in the field are crucial before making investment decisions.''';
  static const String theoryText_2_4 =
      '''In conclusion, different types of investments offer investors a wide range of opportunities to achieve financial goals. Making the right choices and diversifying one's portfolio can help mitigate risks and enhance returns. However, it's essential to be aware that all investments come with risks, so being prepared for potential losses and making decisions based on analysis and financial capabilities is crucial.''';
  static const String theoryText_3_1 =
      '''Risk and return are two crucial aspects of investments that are closely interconnected. In the world of financial investments, risk and return have a direct relationship – the higher the risk, the higher the potential return, and vice versa.
  Risk in investments refers to the possibility of losing part or all of the invested amount. Risks can vary and depend on numerous factors such as the financial condition of a company, political instability, economic conditions, etc. For example, investing in stocks of a highly leveraged company may be associated with a high risk of the company going bankrupt and the loss of investments. Conversely, investing in government bonds may be considered less risky, as governments are typically viewed as reliable borrowers.''';
  static const String theoryText_3_2 =
      '''Return in investments pertains to the potential income or profit that can be gained from investments. Return can be expressed as a percentage or an amount and depends on various factors such as stock price appreciation, dividends, interest payments from bonds, etc. For instance, investing in stocks of a company with high growth potential may lead to significant returns in the future, but it is also associated with a high level of risk.\n
It's important to understand that risk and return in investments are not static and can change over time. Each investor should consider their financial capabilities, goals, and risk tolerance when making investment decisions. Some investors prefer more conservative investments with lower risk and potential returns, while others are willing to take higher risks for the chance of achieving higher returns.''';
  static const String theoryText_3_3 =
      '''To achieve a balance between risk and return in investments, many investors employ a portfolio diversification strategy. Diversification involves spreading investments across different assets, markets, and sectors to reduce risks and increase potential returns. For example, instead of investing the entire amount in one company, an investor may distribute their investments among stocks of different companies, bonds from various issuers, and so on.\n
In conclusion, risk and return are integral parts of investments. Investors should understand that a high level of risk may be associated with high returns, but it also comes with the potential for investment loss. Proper planning, analysis, and portfolio diversification can help investors strike a balance between risk and return and achieve their financial goals.''';
  static const String theoryText_4_1 =
      '''The rules of portfolio diversification are an essential tool for investors seeking to reduce risks and enhance the potential return of their investments. Diversification involves allocating investments across various assets, markets, and sectors to decrease dependence on a specific asset or sector and mitigate potential losses.\n
  The first rule of portfolio diversification involves distributing investments across different asset classes. This means including various types of assets in the portfolio, such as stocks, bonds, real estate, etc. Each of these assets has its own characteristics and risks, and their combination can help reduce the overall level of risk.''';
  static const String theoryText_4_2 =
      '''The second rule of portfolio diversification is to allocate investments across different markets. Investors should consider investing not only in the local market but also in international markets. This can help mitigate risks associated with political and economic instability in a single country or region.\n
  The third rule of portfolio diversification involves distributing investments across different sectors of the economy. Investors should recognize that various sectors may perform differently at different times. Allocating investments across different sectors helps reduce risks associated with making inaccurate predictions about the performance of individual sectors.''';
  static const String theoryText_4_3 =
      '''The fourth rule of portfolio diversification is to regularly rebalance investments. Market conditions and asset performance can change over time, so investors should periodically review their portfolios and make necessary adjustments. Rebalancing allows investors to maintain an optimal balance between risk and return.\n
  The fifth rule of portfolio diversification emphasizes taking into account one's financial capacity and goals. Each investor has unique financial capabilities and objectives. Proper planning and analysis help determine the optimal portfolio diversification strategy that aligns with individual needs and goals.''';
  static const String theoryText_4_4 =
      '''In conclusion, the rules of portfolio diversification serve as a crucial tool for investors aiming to reduce risks and enhance the potential return of their investments. Allocating investments across different assets, markets, and sectors, regular portfolio rebalancing, and considering one's financial capacity and goals help investors achieve a balance between risk and return, ultimately reaching their financial objectives.''';
  static const String theoryText_5_1 =
      '''Analyzing the financial indicators of companies before making investment decisions is a crucial step in the investment process. This analysis allows investors to assess the financial health and development prospects of a company, as well as determine its value and potential profitability.\n
One of the key financial indicators that should be analyzed is the company's profitability. Examining its financial statements, such as the income statement, balance sheet, and cash flow statement, enables an evaluation of how effectively the company generates profit. Investors should pay attention to trends in the company's profitability, as well as its growth and profit stability.''';
  static const String theoryText_5_2 =
      '''Another important financial indicator is the company's liquidity. Investors should assess the company's ability to meet its current obligations and payments, as well as its potential to finance future projects and investments. Analyzing liquidity ratios, such as current ratio and quick ratio, allows investors to evaluate the financial stability of the company.\n
Additionally, investors should analyze the financial structure of the company. This involves assessing its level of debt and ability to pay interest on borrowings. Investors should focus on debt ratios, such as the debt-to-assets ratio and interest coverage ratio, to determine the level of risk associated with investing in the company.''';
  static const String theoryText_5_3 =
      '''It is also crucial to analyze the efficiency of the company's asset utilization. Investors should evaluate how efficiently the company uses its assets to generate profit. Analyzing indicators of asset utilization, such as asset turnover and return on assets, helps investors determine the growth potential and profitability of the company.\n
Finally, investors should analyze the company's market position. This includes evaluating its market share, competitiveness, and growth potential. Analyzing financial indicators such as sales volume, market share, and growth indicators helps investors assess the company's development prospects in the market.''';
  static const String theoryText_5_4 =
      '''In conclusion, analyzing the financial indicators of companies before investing is a crucial step in the investment decision-making process. Evaluating profitability, liquidity, financial structure, asset utilization efficiency, and market position helps investors determine the value and potential profitability of the company, as well as assess the level of risk associated with the investment. Analyzing financial indicators enables investors to make informed decisions and achieve their investment goals.''';
  static const String theoryText_6_1 =
      '''Technical analysis in investments is one of the primary approaches to decision-making in financial markets. It is based on the examination of price and volume charts, along with the use of various technical indicators to forecast future price movements.\n
One key element of technical analysis is trend analysis. A trend represents the direction of price movement in the market, which can be upward (prices gradually rising), downward (prices gradually falling), or sideways (prices fluctuating within a certain range). Trend analysis allows investors to determine the current market situation and make corresponding investment decisions.''';
  static const String theoryText_6_2 =
      '''To analyze trends, investors use various tools such as trendlines, trend channels, and technical analysis patterns like head and shoulders, double bottoms, and triple bottoms. These tools assist investors in determining the market's direction and its prospects.\n
Another crucial aspect of technical analysis involves the use of different technical indicators. A technical indicator is a mathematical formula used to analyze price and volume charts. It helps investors identify buying and selling points for stocks and forecast future prices.''';
  static const String theoryText_6_3 =
      '''Some of the most common technical indicators include moving averages, relative strength, and stochastic oscillator. Moving averages represent the average price over a specific period and are used to determine the overall trend direction. Relative strength compares the performance of a single stock to the overall market, aiding in identifying its relative strength or weakness. The stochastic oscillator indicates how quickly prices are changing and helps determine whether a stock is overbought or oversold.\n
Technical analysis enables investors to make informed decisions based on past price movements and trading volumes. It assists in identifying buying and selling points for stocks and forecasting future prices. However, it is important to remember that technical analysis is not a guarantee of success and should be used in conjunction with other methods of analysis and risk assessment.''';
  static const String theoryText_6_4 =
      '''In conclusion, technical analysis is a crucial tool in investments, allowing investors to analyze price charts, trends, and use various technical indicators for decision-making. It helps investors identify buying and selling points for stocks and forecast future prices. However, it is essential to remember that technical analysis is not the sole tool and should be used in combination with other methods of analysis and risk assessment.''';
  static const String theoryText_7_1 =
      '''Fundamental analysis in investments is one of the primary approaches to assessing the value of assets and companies. It is based on the examination of fundamental factors such as financial indicators, economic conditions, and industry trends to determine the true value of an asset or company.\n
One of the key elements of fundamental analysis is the analysis of a company's financial indicators. Investors study income statements, balance sheets, and cash flows to evaluate the financial health and performance of a company. They also analyze profitability, liquidity, and financial stability indicators to assess the company's reliability and success.''';
  static const String theoryText_7_2 =
      '''Another crucial aspect of fundamental analysis is the evaluation of economic conditions and industry trends. Investors examine macroeconomic indicators such as GDP, inflation, and unemployment to determine the overall economic situation and its impact on the company. They also analyze industry trends, such as technological innovations and changes in consumer demand, to assess the prospects for the industry and the company.\n
To assess the value of assets and companies, investors use various methods such as discounted cash flow, price-to-earnings (P/E) ratio, price-to-book (P/B) ratio, and others. These methods enable investors to determine whether an asset or company is overvalued or undervalued in the market.''';
  static const String theoryText_7_3 =
      '''Fundamental analysis allows investors to make informed decisions based on data about financial indicators, economic conditions, and industry trends. It helps determine the true value of assets and companies and make decisions about buying or selling. However, it is essential to remember that fundamental analysis is not a guarantee of success and should be used in conjunction with other methods of analysis and risk assessment.\n
In conclusion, fundamental analysis is an important tool in investments that enables investors to assess the value of assets and companies based on financial indicators, economic conditions, and industry trends. It helps make informed decisions about buying or selling assets. However, it is crucial to remember that fundamental analysis is not the sole tool and should be used in combination with other methods of analysis and risk assessment.''';
  static const String theoryText_8_1 =
      '''Investing is the process of making decisions about allocating financial resources with the goal of generating profits. However, despite being rooted in logic and data analysis, investments are also heavily influenced by the emotions of the investor.\n
Emotions play a significant role in investment decision-making. Investors may experience joy when making a profit, anger when facing losses, or fear of potential risks. All these emotions can impact decision-making and even lead to irrational actions.''';
  static const String theoryText_8_2 =
      '''One of the most common emotions associated with investing is fear. Investors may fear losing money or taking risky decisions, leading them to make conservative choices and miss out on profit opportunities. For instance, they might avoid investing in new and promising companies due to fear of the unknown.\n
Another emotion that can influence investment decisions is greed. Investors may be tempted by high returns and seek maximum profit. However, greed can lead to risky investments and financial losses. Investors might ignore warnings and analytical data in pursuit of satisfying their greed, resulting in incorrect decisions and significant financial setbacks.''';
  static const String theoryText_8_3 =
      '''Moreover, emotions can affect decisions regarding the timing of investments. Investors might fear missing out on high returns and make impulsive decisions without proper analysis. Conversely, they may delay investments due to fear of losing money. Both approaches can be flawed and lead to missed income opportunities.\n
To avoid the negative impact of emotions on investment decisions, it is crucial to develop a strategy and adhere to it. Investors should base their decisions on data and facts rather than emotions. Establishing goals and risks in advance can provide a clear understanding of what to expect from investments.''';
  static const String theoryText_8_4 =
      '''Additionally, investors can turn to professional consultants or psychologists for advice and support in decision-making. This can help them better understand their emotions and control their influence on investment decisions.\n
In conclusion, psychology plays a vital role in investments. Emotions can affect decision-making and result in incorrect investments or financial losses. However, conscious awareness of emotions and the development of a strategy can help investors control their decisions and achieve success in investments.''';
  static const String theoryText_9_1 =
      '''Investing for the long term is one of the most effective ways to achieve financial success. These strategies are based on the principle of long-term growth, allowing investors to secure stable profits over an extended period.\n
One such strategy is passive investing. This approach involves creating a portfolio comprising a broad range of assets, such as stocks, bonds, and real estate, and holding onto these assets for the long term. It relies on the principle of long-term growth and risk minimization.''';
  static const String theoryText_9_2 =
      '''Passive investing assumes that the market, as a whole, will grow over time. Therefore, investors opt for a well-diversified portfolio to minimize risks and attain average market returns. Instead of active trading and attempting to predict future market changes, investors follow a "buy and hold" strategy, retaining assets for an extended period.\n
Another long-term investment strategy is diversification. This approach involves spreading investments across different asset classes, regions, and industries. The goal of diversification is to reduce risks and enhance potential returns. Allocating investments among stocks, bonds, real estate, and other assets enables investors to protect their capital from potential losses and gain profits from various sources.''';
  static const String theoryText_9_3 =
      '''Long-term investment strategy also includes regular portfolio rebalancing. This means that investors periodically readjust their investments according to goals and strategy. For instance, if stocks in one industry significantly rise while stocks in another industry fall, investors might sell some shares of the first industry and acquire shares in the second. This allows for maintaining a long-term balance in the portfolio and avoiding excessive risk concentration.\n
However, long-term investment strategies are not flawless. They demand patience, discipline, and constant monitoring. Investors should be prepared for market fluctuations and prolonged periods of reduced returns. It is also crucial to consistently update knowledge and stay informed about changes in the economy and financial markets.''';
  static const String theoryText_9_4 =
      '''In conclusion, long-term investment strategies are effective means to achieve financial success. Built on the principle of long-term growth and risk minimization, strategies like passive investing, diversification, and portfolio rebalancing are key elements. However, successful long-term investing requires patience, discipline, and ongoing monitoring.''';
  static const String theoryText_10_1 =
      '''Trading on the stock market is one of the most popular ways to invest and achieve financial success. However, to be a successful trader, it is essential to familiarize oneself with the fundamental rules and strategies of this form of investing.\n
The first rule of stock market trading is risk management. Successful traders always have a strict risk management system in place to minimize potential losses. They define their maximum acceptable risk level for each trade and adhere to it. Additionally, they use stop-loss orders to safeguard their positions from significant losses.''';
  static const String theoryText_10_2 =
      '''The second rule is the development of a trading strategy. Successful traders have a clear and well-thought-out strategy based on market analysis and the prediction of market movements. They identify entry and exit points for trades and set profit targets. They may also utilize various technical indicators and oscillators to make informed decisions.\n
The third rule is continuous learning and analysis. Successful traders constantly seek to update their market knowledge and stay informed about market changes. They study new trading strategies, analyze their mistakes, and learn from them. They also keep an eye on news and economic events that may impact the market.''';
  static const String theoryText_10_3 =
      '''One trading strategy on the stock market is trend trading. This strategy assumes that stock prices tend to move in one direction over a specific period. Traders identify market trends and open positions in the direction of these trends. They may use various indicators, such as moving averages, to determine the trend's direction.\n
Another popular strategy is day trading. In this strategy, traders open and close positions within a single day. They look for short-term price movements and attempt to profit from them. This strategy requires quick reactions to market changes and the use of technical indicators to make decisions.''';
  static const String theoryText_10_4 =
      '''It's important to note that trading on the stock market is not flawless and comes with risks. The market can be volatile and subject to changes that may impact trading outcomes. Therefore, traders must be prepared for potential losses and have a risk management strategy in place.\n
In conclusion, trading on the stock market requires knowledge of fundamental rules and strategies. Risk management, the development of a trading strategy, and continuous learning are key components of successful trading. Trend trading and day trading are popular strategies among traders. However, trading on the stock market also involves risks, and traders must be prepared for potential losses.''';
  static const String theoryText_11_1 =
      '''Investing in startups and venture projects is one of the most promising and effective ways to deploy capital. This is due to the fact that startups are young companies with significant potential for growth and development.\n
One of the primary reasons why investors choose startups is the opportunity to achieve high returns on their investments. Startups possess the potential for rapid growth and can deliver substantial results in a relatively short period. Consequently, investors have the chance to gain significant profits from their investments.''';
  static const String theoryText_11_2 =
      '''Furthermore, investing in startups allows for portfolio diversification. Diversifying assets helps reduce risks and enhance investment stability. Venture projects often involve innovative and unique ideas, serving as an additional income source for investors.\n
Another advantage of investing in startups is the opportunity for active participation in the company's development and growth. Investors can contribute their expertise, knowledge, and networking, aiding the startup in achieving success. Thus, investing in startups becomes not only financial support but also a form of strategic partnership.''';
  static const String theoryText_11_3 =
      '''However, it's essential to note that investing in startups and venture projects comes with certain risks. Many startups do not succeed and may close, leading to potential investment losses. Therefore, thorough analysis and risk assessment are necessary before deciding to invest in a startup.\n
In conclusion, investing in startups and venture projects is a promising and profitable form of investment. It offers the potential for high returns, portfolio diversification, and active involvement in a company's development. Nevertheless, it's crucial to be mindful of the associated risks and conduct a thorough analysis before making investment decisions.''';
  static const String theoryText_12_1 =
      '''In recent years, cryptocurrencies and blockchain technology have become the focus of widespread attention. Cryptocurrencies such as Bitcoin, Ethereum, and Ripple represent digital assets built on blockchain technology. Blockchain is a distributed database that stores transaction information, providing security and transparency.\n
One of the primary capabilities of cryptocurrencies and blockchain is streamlining and accelerating financial transactions. Traditional financial systems can be slow and costly, especially for international transfers. Cryptocurrencies enable instant and cost-effective transactions without intermediaries.''';
  static const String theoryText_12_2 =
      '''Blockchain technology can also enhance transparency and security across various industries. For instance, in supply chain management, blockchain can be used to trace products from manufacturers to consumers, improving product quality and safety. In the realm of voting, blockchain can ensure transparency and prevent election result manipulation.\n
However, cryptocurrencies and blockchain come with their set of risks. One major risk is the volatility of cryptocurrency prices. Prices of Bitcoin and other cryptocurrencies can experience significant fluctuations, leading to substantial losses for investors. Additionally, cryptocurrencies are susceptible to the risk of cyberattacks and hacking incidents. Despite blockchain providing high security, breaches of cryptocurrency exchanges and wallets remain possible.''';
  static const String theoryText_12_3 =
      '''Another risk involves the lack of regulation. Cryptocurrencies and blockchain belong to emerging technologies, and the legal framework for them is still not fully developed. This uncertainty can create risks for investors and users.\n
Despite these risks, cryptocurrencies and blockchain offer significant opportunities for innovation and development. Blockchain can enhance efficiency and transparency in various sectors, including finance, healthcare, and governance. Cryptocurrencies can serve as alternative means of payment and savings, especially in countries with limited access to traditional financial services.''';
  static const String theoryText_12_4 =
      '''In conclusion, cryptocurrencies and blockchain present opportunities for simplifying and expediting financial transactions and enhancing transparency and security across different industries. However, they also come with risks such as price volatility, cyberattacks, and lack of regulation. Therefore, it is crucial to be informed about these risks and take appropriate measures to minimize them.''';
  static const String theoryText_13_1 =
      '''Investing in one's own business, especially in the creation and development of a startup, is one of the most thrilling and promising forms of entrepreneurial activity. It allows individuals not only to invest their financial resources but also to bring their ideas, creative potential, and entrepreneurial spirit to life.\n
Launching a startup involves creating a new business based on innovative and unique ideas. It could be a new product or service that differs from existing offerings on the market or a novel approach to an existing business. Investors choosing to allocate funds to such a startup see the potential for growth and success.''';
  static const String theoryText_13_2 =
      '''The development of a startup requires not only financial investment but also intensified efforts in promoting the product or service in the market. Investors can assist in this process by providing not only financial support but also their experience and knowledge. They can actively participate in strategic planning, conduct marketing research, and assist in finding clients and partners.\n
Investing in one's own business has several advantages. Firstly, it allows for controlling the entire development process and making strategic decisions. In contrast to investing in external startups, where investors may have limited control over the company, investing in one's own business provides the opportunity to have complete control over processes and make all decisions independently.''';
  static const String theoryText_13_3 =
      '''Secondly, investing in one's own business enables maximizing profits. In the case of successful startup development, its value can significantly increase, resulting in high returns for the investor. Additionally, owning one's own business provides the opportunity to receive stable and consistent income in the future.\n
However, investing in one's own business also comes with certain risks. Launching and developing a startup requires substantial financial investment, as well as time and effort. Not all startups achieve success, and some may close down, leading to a loss of investments. Therefore, before deciding to invest funds in one's own business, a thorough analysis of the market, competitors, and the potential profitability of the project is necessary.''';
  static const String theoryText_13_4 =
      '''In conclusion, investing in one's own business, especially in launching and developing a startup, presents an exciting and promising opportunity. It allows individuals not only to invest their financial resources but also to bring their ideas and entrepreneurial potential to life. However, it is crucial to be mindful of the risks and conduct a thorough analysis before making decisions.''';
  static const String theoryText_14_1 =
      '''Investing in real estate is one of the most popular and long-term methods of capital investment. This is due to several advantages that real estate offers, such as stability, income generation, and portfolio diversification opportunities.\n
One primary method of real estate investment is through property acquisition. Purchasing real estate allows investors to earn income through rent or potential future property sales. Additionally, real estate values typically appreciate over time, potentially resulting in profits upon subsequent sales. Property acquisition also provides the opportunity to control the property and make improvements to enhance its value.''';
  static const String theoryText_14_2 =
      '''Another method of real estate investment is through leasing. An investor can acquire property and lease it, generating regular income from rental payments. Leasing can be an attractive strategy for investors who prefer not to engage in property management or lack the capital for outright property purchases.\n
Real estate development represents another avenue for investment in this industry. An investor can acquire land or an existing property, investing funds in its renovation or the construction of a new structure. Real estate development can be highly profitable, especially if the property is located in a promising area or offers unique services or opportunities.''';
  static const String theoryText_14_3 =
      '''However, real estate investment comes with its share of risks. One of the main risks is the fluctuation in the market value of the property. Real estate prices can vary based on economic conditions and market demand. Additionally, investors may face challenges related to tenants, such as rent non-payment or property damage.\n
Financial considerations are crucial when investing in real estate. For property purchases, factors such as acquisition costs, taxes, commissions, and ongoing maintenance expenses need to be taken into account. When leasing, analyzing the market and selecting reliable tenants is essential to minimize the risk of income loss.''';
  static const String theoryText_14_4 =
      '''Despite the risks, real estate investment can be a lucrative and stable means of capital investment. Real estate possesses intrinsic value, with the potential for appreciation over time, making it attractive to investors. Furthermore, real estate serves as a tangible asset that can be leveraged for loans or passive income generation.\n
In conclusion, real estate investment presents significant opportunities for income generation and portfolio diversification. Property acquisition, leasing, and development are the main avenues for capital investment in this industry. However, it is crucial to consider the associated risks and take appropriate measures to minimize them, such as conducting market analysis and selecting reliable partners.''';
  static const String theoryText_15_1 =
      '''Investing in art and collecting is one of the distinctive and captivating ways to allocate funds. It not only offers the potential for financial gains but also allows individuals to immerse themselves in the world of creativity and culture, enjoying the beauty of art.\n
Art has a long history and is an integral part of human civilization. Paintings, sculptures, photographs, antiques—all serve as collectibles and can hold significant value. Collectors and investors choosing to invest in art see it not only as an opportunity to make money but also as a means to preserve cultural heritage and support talented artists.''';
  static const String theoryText_15_2 =
      '''One advantage of investing in art is its resilience to economic fluctuations. Unlike stocks or real estate, the value of artworks is not solely dependent on market trends. While there may be fluctuations in the prices of individual pieces, art, in general, maintains its value and can even appreciate over time.\n
Investing in art also provides unique emotional and aesthetic experiences. Collecting works of art offers a chance to immerse oneself in the world of creativity and appreciate its beauty. Each artwork has its own history, energy, and uniqueness. Owning such pieces brings joy and satisfaction.''';
  static const String theoryText_15_3 =
      '''However, investing in art comes with its own set of risks. Determining the value of an artwork can be a complex and subjective process. The price may depend on various factors such as authorship, rarity, condition, the popularity of the artist, and more. Additionally, there is a risk of acquiring a forgery or a work of questionable quality.\n
Therefore, before diving into art investment and collecting, thorough analysis and professional consultations are necessary. Investors can seek guidance from experts and curators who can help assess the value, authenticity, and growth potential of an artwork.''';
  static const String theoryText_15_4 =
      '''In conclusion, investing in art and collecting presents a unique opportunity that combines financial benefits with aesthetic satisfaction. It allows individuals not only to make money but also to revel in the beauty of art, preserve cultural heritage, and support talented artists. However, it's essential to be mindful of the risks and conduct a thorough analysis before making investment decisions.''';
  static const String theoryText_16_1 =
      '''Retirement planning and investments are crucial aspects of financial planning for every individual. With the increasing average lifespan and the instability of state pension systems, more people are turning to investments to secure their future.\n
Retirement planning involves the process of setting goals and strategies to achieve financial independence after retiring. It includes assessing current financial capabilities, determining the required sum for a comfortable retirement, and devising a plan for accumulating funds.''';
  static const String theoryText_16_2 =
      '''Investments play a key role in retirement planning as they enable the growth of savings over an extended period. Diverse investment instruments such as stocks, bonds, real estate, investment fund shares, and others offer the opportunity for higher returns compared to simply storing funds in a bank account.\n
One of the primary benefits of investing in retirement planning is the opportunity to leverage tax advantages. Many countries have special retirement accounts or programs allowing individuals to defer money for retirement with minimal or even no taxation. This significantly enhances the effectiveness of investments and helps accumulate a larger sum by the time of retirement.''';
  static const String theoryText_16_3 =
      '''However, investments also come with risks, especially in the short term. Financial markets can experience fluctuations and instability, leading to the loss of a portion of the investments. Therefore, when planning for retirement and selecting investment strategies, one must consider their financial profile, risk tolerance, and the time remaining until retirement.\n
For successful retirement planning and investing, seeking guidance from a financial consultant or specialist is recommended. They can assist in determining the optimal strategy and choosing suitable investment instruments. They help evaluate the current situation, set goals, and develop an action plan to achieve financial independence in retirement.''';
  static const String theoryText_16_4 =
      '''In conclusion, retirement planning and investments are integral parts of every individual's financial planning. They enable a comfortable retirement and financial independence. However, it's essential to consider risks and seek professional assistance when developing a retirement plan and selecting investment strategies.''';
  static const String theoryText_17_1 =
      '''Investing in gold and precious metals is one of the most popular capital investment strategies. Gold, silver, platinum, and other precious metals have a long history of being used as a medium of exchange and a store of value. Their intrinsic value and stability make them attractive to investors, especially during periods of economic instability.\n
One of the primary advantages of investing in gold and precious metals is their ability to preserve value over the long term. Unlike other assets, such as stocks or bonds, the price of gold and precious metals is generally not subject to significant fluctuations. This makes them a reliable means of protecting against inflation and economic instability.''';
  static const String theoryText_17_2 =
      '''Furthermore, investing in gold and precious metals provides an opportunity for portfolio diversification. Asset diversification is a crucial aspect of successful investing as it helps reduce risk and increase potential returns. Including gold and precious metals in a portfolio helps balance risks and ensures stability during periods of financial market uncertainty.\n
Another advantage of investing in gold and precious metals is their liquidity. Gold and other precious metals can be easily converted into cash or other assets. This makes them appealing to investors who want the flexibility to quickly convert their investments into money.''';
  static const String theoryText_17_3 =
      '''However, investing in gold and precious metals comes with its own set of risks. One of the main risks is the fluctuation in metal prices on global markets. Prices of gold and other precious metals can vary depending on factors such as economic conditions, political instability, and market demand. Investors should be prepared for potential losses associated with changes in metal prices.\n
It is also essential to consider the financial aspects of investing in gold and precious metals. When purchasing metals, investors need to account for the cost of acquisition, fees, and storage expenses. Additionally, investors should exercise caution in choosing a storage method to minimize the risk of theft or loss.''';
  static const String theoryText_17_4 =
      '''In conclusion, investing in gold and precious metals presents significant opportunities for investors. They offer stability, liquidity, and the ability to preserve value over the long term. However, investors must be prepared for potential risks associated with changes in metal prices. It is crucial to consider financial aspects and take appropriate measures to protect investments.''';
  static const String theoryText_18_1 =
      '''Investing in funds and Exchange-Traded Funds (ETFs) is one of the most popular methods of capital investment in today's financial markets. These instruments provide investors with the opportunity to diversify their portfolios, reduce risks, and generate stable income.\n
Funds and ETFs represent a collection of assets, such as stocks, bonds, commodities, or real estate, managed by professional fund management companies. Investors can purchase shares of these funds and ETFs on the stock exchange, allowing them to earn returns from the growth in the value of assets within the fund.''';
  static const String theoryText_18_2 =
      '''One of the primary advantages of investing in funds and ETFs is portfolio diversification. Funds and ETFs typically consist of a broad range of assets, enabling investors to spread their risks across various instruments. For instance, if the stocks of one company in the portfolio decline, other assets within the fund may compensate for these losses.\n
Another advantage of investing in funds and ETFs is professional management. Management companies have the expertise and knowledge to make investment decisions, along with access to information and analytics that can help them select the most promising assets. This allows investors to reduce their research and market analysis costs.''';
  static const String theoryText_18_3 =
      '''Moreover, investing in funds and ETFs offers high liquidity. Investors can buy and sell shares of these funds on the stock exchange at any time, allowing them to quickly respond to market changes or their financial needs.\n
However, like any other form of investment, investing in funds and ETFs is not without risks. Market fluctuations, political and economic events can impact the value of assets within the fund. Additionally, fees and management expenses may reduce the profitability of investments.''';
  static const String theoryText_18_4 =
      '''In conclusion, investing in funds and ETFs is an attractive method for investors looking to diversify their portfolios, mitigate risks, and achieve stable income. However, before deciding to invest in funds and ETFs, thorough research and market analysis are essential, considering one's financial goals and risk profile.''';
  static const String theoryText_19_1 =
      '''Social investing involves financial investments made with the aim of achieving social impact and sustainable development. In contrast to traditional investments, where the primary goal is profit, social investments focus on addressing social issues and improving people's quality of life.\n
One of the key aspects of social investing is philanthropy. Charitable organizations and funds attract financial resources to implement various projects aimed at helping those in need. Social investors can invest money in such organizations to support their activities and contribute to addressing social problems, such as combating poverty, ensuring access to education and healthcare, environmental protection, and more.''';
  static const String theoryText_19_2 =
      '''In addition to philanthropy, social investing also contributes to sustainable development. Investors can fund projects that promote economic growth and job creation, taking into account social and environmental aspects. For example, investments in renewable energy help reduce dependence on fossil fuels and decrease greenhouse gas emissions, contributing to environmental preservation and improving people's quality of life.\n
Social investing has not only financial but also social value. It allows investors not only to make a profit but also to contribute to solving social problems and promoting sustainable development in society. Moreover, such investments can be a powerful tool for systemic change and the creation of a more just and sustainable world.''';
  static const String theoryText_19_3 =
      '''In conclusion, social investing is an effective tool for achieving philanthropy and sustainable development. It enables investors to contribute to solving social problems, improving people's quality of life, promoting economic growth, and preserving the environment. Social investing is not just about financial investments; it's an opportunity to make the world a better place.''';
  static const String theoryText_20_1 =
      '''Investing in education and personal growth stands out as one of the most significant and promising avenues for social investment. Education plays a pivotal role in societal development and shaping the future generation. It not only imparts knowledge and skills but also contributes to unlocking individuals' potential, fostering critical thinking, independence, and a creative problem-solving approach.\n
Investments in education can be directed toward various aspects of this sphere, ranging from creating accessible and high-quality learning conditions to supporting talented students and scientific research. Financing educational programs and projects helps broaden access to education for all layers of the population, including underprivileged families and remote regions. This contributes to reducing educational inequality and creating equal opportunities for everyone.''';
  static const String theoryText_20_2 =
      '''Investing in education also supports personal growth. It aids individuals in realizing their potential, developing the skills and competencies necessary for a successful career and personal life. Education contributes to the formation of values, ethical principles, and tolerance, forming the foundation for a civil society and democratic development.\n
Investing in education and personal growth yields long-term benefits for society. Qualified and educated individuals can contribute to the economy, innovation, and the country's development. They become active participants in society, capable of making informed decisions and bringing about positive changes. Furthermore, investments in education reduce social costs associated with unemployment, crime, and low levels of well-being.''';
  static const String theoryText_20_3 =
      '''However, investing in education and personal growth requires a systemic approach and collaboration between the government, business, and civil society. Conditions need to be created for the development of quality education, ensuring accessibility and equal opportunities for all, and supporting innovation and scientific research.\n
In conclusion, investing in education and personal growth is a key factor in sustainable societal development. It contributes to the formation of qualified and responsible citizens, the creation of equal opportunities, and the reduction of social costs. Investments in education are investments in the future, enabling individuals to unlock their potential and contribute to societal development.''';
}
